### PR TITLE
[#1] support for UNIX socket

### PR DESCRIPTION
**Pull request by nagata-logly**
@kazuho @miyagawa
This is a least modification for UNIX socket.
My psgi work fine by this modification.

But `t/03-unix.t` have same error.

```
Bad arg length for Socket::unpack_sockaddr_in, length is 2, should be 16 at lib/5.16.0/x86_64-linux/Socket.pm line 790, <DATA> line 16.
```

Could you something help?

### CODE REVIEW

**Comment by nagata-logly** [comment]
@kazuho @miyagawa
I resoved a error.
But this has more 2 problems.
- It needs 2 times new IO::Socket::UNIX
- `getppid` get a start_server pid

Could you something help?

**Comment by kazuho** [comment]
@nagata-logly Thank you for the PR.

Changes to PreFork.pm looks good to me :+1:

On the other hand I have a difficulty in understanding what you are trying to accomplish with the tests.  I believe that the test should use Net::Server to start a server, and check that it works (in other words, much like what is done in 01-httpd.t, but with using an Unix socket).  However, your test does not seem to be doing something like that.

Could you please either update the tests or clarify how you are testing the feature implemented by the PR?

PS. 日本語でも英語でもどちらでも構いません。

**Comment by nagata-logly** [comment]
@kazuho @miyagawa
I got it !!
Maybe all went well.

PS. When You came close to the shibuya, please come to play.

**Comment by nagata-logly** [comment]
oops...

**Comment by nagata-logly** [comment]
@kazuho 
How do you think this?
It has a problem yet?
Please tell me good or bad.
Have a nice day.

**Comment by zebardy** [comment]
Hi,

I've hit the bug solved by this pull request. @kazuho @miyagawa, is there anything I can do to help get a fix merged? I'm happy to do some work improving tests, or refactoring things.

Thanks

**Comment by miyagawa** [comment]
@zebardy what is the bug? My understanding is this PR is a new feature addition and not a bug fix.

**Comment by zebardy** [comment]
@miyagawa I get your point, this is technically not a bug as Net::Server::SS::PreFork does not make any promise or suggestion to work with unix sockets. Thanks @kazuho for merging the pull request.

**Comment by bay** [comment]
@kazuho Can you please make it available in CPAN so that it can be installed with carton?

**Pull request merged**
